# Generated by Django 4.2.16 on 2024-11-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_return_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="fcm_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
